### ISSUE TITLE
Request: Allow the slider to be 'segmented' and allow labels per segment.

### ISSUE THREAD

**Issue by waxxxd** [simeydotme/jQuery-ui-Slider-Pips#101]
It would be useful aesthetically to segment to slider while maintaining the pips and then addion labels to the segments. i.e. Low, medium, high labels as in temperature on a slider ranging from -20 to 40.

**Comment by simeydotme** [comment]
if I understand you correctly, this is easy to achieve aesthetically, however it doesn't make any sense UX wise.

http://jsfiddle.net/wnzag0ce/1/
it's a little "hacky" with the labels array, but I'm sure it satisfies your intentions :)
