### ISSUE TITLE
Custom style for slider.

### ISSUE THREAD

**Issue by lk-geimfari** [simeydotme/jQuery-ui-Slider-Pips#103]
Can i  stylize slider like in image? Is it possible?

![](http://i.imgur.com/NS9T25E.png)

Here first element of range is Russian letter `Д`. Empty part of slider is just stylized first element, i.e index of this element `Д` is 0.

**Comment by simeydotme** [comment]
Do you mean you want to style with a large empty space at the start?

Please, can you create a test-fiddle (from the readme.md) with what you currently have, and I can try to help you achieve what you would like :)

**Comment by lk-geimfari** [comment]
Yes, style with large space before first element of slider and before last element. 

[Here](http://codepen.io/likid_geimfari/pen/pRMPmP) you can see a pen.

Thank you.

**Comment by simeydotme** [comment]
here you go;
http://codepen.io/simeydotme/pen/gmwmMX

Actually it was all achievable with css! 👍 
(_i left the additions in red, so they're easy to spot and change_)

**Comment by simeydotme** [comment]
That should work perfectly fine in IE8+

**Comment by lk-geimfari** [comment]
@simeydotme Awesome! Thank you, Simon. How about add this plugin to [awesomo](https://github.com/lk-geimfari/awesomo)?
