### ISSUE TITLE
How to disable label on slider?

### ISSUE THREAD

**Issue by lk-geimfari** [simeydotme/jQuery-ui-Slider-Pips#104]
Is it possible to disable selected label (index) of slider?

Example: 
![image](https://cloud.githubusercontent.com/assets/15812620/24602482/9c37ce56-1865-11e7-9dd3-7ae56032bce3.png)

Or:
```js
var main = ["A", "B", "C", "D", "E"]
var available = ["A", "B", "D"];
```
And i want to create slider with all labels from `main`, but only labels from `available` will active.

Here you can see grey labels which are not active. Can i do them inaccessible when user change position of pointer?

Live demo of my slider available [here](http://codepen.io/likid_geimfari/pen/JWjyVY)

**Comment by simeydotme** [comment]
Please can you elaborate? I don't understand.
Perhaps a diagram would help?

The answer is probably; Yes. But without knowing what you are looking for I cannot provide the solution :)

**Comment by lk-geimfari** [comment]
@simeydotme Sorry. I already found a solution. Thank you!

**Comment by lk-geimfari** [comment]
@simeydotme Look, please.
