### ISSUE TITLE
Can we have a user defined multiple pips values ?

### ISSUE THREAD

**Issue by sharathbangera6** [simeydotme/jQuery-ui-Slider-Pips#106]
Hi,

Wanted to know if we can have the user defined pips value for example an array [1 , 2, 5.5, 6, 9 , 11, 12, etc...]

Thank You
Sharath

**Comment by simeydotme** [comment]
Did you read the documentation?

**Comment by sharathbangera6** [comment]
What i wanted to ask is can we have irregular intervals and have space between these numbers as per the interval. for ex: [1,2,5.5,10,11,17,23,47,55] and the space between these points should not be equally distributed.

**Comment by certainlyakey** [comment]
I follow that. This one is not mentioned in the docs.

**Comment by simeydotme** [comment]
Here: http://jsfiddle.net/djfLtgkn/13/

**Comment by certainlyakey** [comment]
For me this ticket is about irregular intervals for ticks with only one slider handle snapping to them (not multiple handles).

**Comment by simeydotme** [comment]
sorry, that's not the way jQueryUI slider works :)

**Comment by simeydotme** [comment]
but you could always write your own JS ... like;

```
if ( sliderStopsOnANumberBetweenInterval ) {
  moveSliderHandleToClosestInterval();
}
```
