### ISSUE TITLE
Double labels in IE

### ISSUE THREAD

**Issue by PhpSriptKiddie** [simeydotme/jQuery-ui-Slider-Pips#107]
Hey there,

It seems like the double labels are shown wrong in IE: http://oi67.tinypic.com/2cy1cn7.jpg

Any way to fix this?

Thanks

**Comment by simeydotme** [comment]
Hey @PhpSriptKiddie ... that'll just be a CSS alignment I overlooked for IE 😄  -- you just need to edit the CSS to fit your purposes 🙇‍♀️

**Comment by PhpSriptKiddie** [comment]
Thanks - but when I fix it for IE, it is shown wrong in Chrome instead. Any ideas to get it right in all browsers? Ty!
