### ISSUE TITLE
Uncaught Error: no such method 'pips' for slider widget instance

### ISSUE THREAD

**Issue by PeteHalsted** [simeydotme/jQuery-ui-Slider-Pips#109]
I recently updated my development environment. It is a non standard environment, and I am sure my issue has something to do with the extension getting stepped on by something else, but I am hoping you can give me some ideas of what to look for? A google search find one other person with a similar issue when trying to use with Word Press but there were no answers. 

My based code is the same and didn't change, I am loading jquery and jqueryui. Slider works, just seems that the extend is not working for some reason.  

Any hits or suggested would be welcomed.

**Comment by simeydotme** [comment]
it usually means the pips plugin was not loaded before you try to execute it... without seeing your environment I can't really help further... just make sure the script is loading before you execute the `pips` method :)

**Comment by vinhtq** [comment]
I have the same issue.

I followed the guide by importing these libs:
```
<!-- include the jQuery and jQuery UI scripts -->
<script src="https://code.jquery.com/jquery-2.1.1.js"></script>
<script src="https://code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
                
<!-- plus a jQuery UI theme, here I use "flick" -->
<link rel="stylesheet" href="https://code.jquery.com/ui/1.10.4/themes/flick/jquery-ui.css">
```

What's else do I need?

**Comment by simeydotme** [comment]
https://jsfiddle.net/1f3fuoyg/
^^ here, please use this for example :)
