### ISSUE TITLE
Plugin unstable on Safari V9.1.2

### ISSUE THREAD

**Issue by ireydiak** [simeydotme/jQuery-ui-Slider-Pips#110]
The plugin is very unstable on Safari V9.1.2. I haven't tested it on the latest version but it seems like certain sliders are not being displayed. I first thought it was an issue in my own css but then I looked up your website and noticed the same issue there. See the screenshot below for more details.

![screen shot 2017-06-13 at 1 11 56 pm](https://user-images.githubusercontent.com/14093084/27095019-2a264aba-503a-11e7-9076-a3c50871682d.png)

**Comment by simeydotme** [comment]
what happened?

**Comment by ireydiak** [comment]
I'm not sure yet but I think I jumped to conclusions too quickly.

Very sorry for the noise I created on your github with that entry.

I was simply reporting a bug but I've been assigned to other projects before I could dig into the problem.

I don't think it's related to the plugin hence why I deleted the entry.


Jean-Charles


________________________________
De : Simon Goellner <notifications@github.com>
Envoyé : 16 juin 2017 20:03
À : simeydotme/jQuery-ui-Slider-Pips
Cc : Igor Reydiak; State change
Objet : Re: [simeydotme/jQuery-ui-Slider-Pips] Plugin unstable on Safari V9.1.2 (#110)


what happened?

**Comment by simeydotme** [comment]
alright, thanks! :)
feel free to re-open if you ever figure it out

**Comment by ireydiak** [comment]
I found out what the issue was. 
 
Basically I was using a forEach function from a document.querySelectorAll result. That operation returned a HTML collection instead of an array, hence the sliders were not displayed. However this issue was not present on Chrome and Firefox. 

The plugin has no compatibility issue with Safari.
Sorry again for the noise.
