### ISSUE TITLE
Pips doesn't work on the mobile

### ISSUE THREAD

**Issue by jeev92** [simeydotme/jQuery-ui-Slider-Pips#115]
hi,

my slider works well on the normal mode.when i switch it to the mobile mode using chrome tools,the slider doesnt update any records when clicked on pips,but it does well when dragged

**Comment by richardmbell** [comment]
Interesting that you just posted this.  We are experiencing the same problem.  We have included the jquery.ui.touch-punch library as well.  When clicking on a pip, it does not trigger the slidechange event.  It does trigger the change event, but we can not use 'change'.  It seems like slidechange should also be triggered.

**Comment by simeydotme** [comment]
hey thanks for raising this :)

Actually, chrome devtools has some problems emulating mobiles accurately, especially with regards to touch sensors. Could you test on a real device as I am certain it should be working ok. My devtools seems fine, also.
