### ISSUE TITLE
ui-slider-pip-selected losing class when clicking button

### ISSUE THREAD

**Issue by pgroot91** [simeydotme/jQuery-ui-Slider-Pips#116]
Somewhere along the way it seems that when i click another button in the application the following classes  **ui-state-focus** and **ui-slider-pip-selected** will looses its state. Is there a way to prevent losing it's state/class? And force it to be a **ui-slider-pip-selected**.

**Comment by simeydotme** [comment]
Hi @pgroot91 ... Please can you demonstrate this with a JSFiddle?

`ui-state-focus` is part of jQueryUI, nothing I can do about that. But `ui-slider-pip-selected` should remain as long as that pip is selected.

**Comment by pgroot91** [comment]
Will see what i can do and try collect the code of the button/slider and will try to put in JSFiddle if i can and make it work like that for demonstration.

**Comment by pgroot91** [comment]
👌 I figured it out i broke it myself! 

What im trying to do here is to reverse te slider. In this case the speed.

It's going from fast to slow. I like it to be the other way arround from slow to fast.

`$("#slider").slider({
        min: 0,
        max: 4000,
        value: 0,
        step: 800
    }).slider("pips", {
        rest: "label", labels: ["Slow", "800", "1600", "2400", "3200", "&#xe984;"]
    });`

Any suggestion how i could acomplish that?
