### ISSUE TITLE
Problem with labels

### ISSUE THREAD

**Issue by 034034** [simeydotme/jQuery-ui-Slider-Pips#118]
Hi, 

Can anyone help me to solve problem with this  code?
           `
var sliderLabels = ["Step 1", "Step 2", "Step 3","Step 4"];

            $("[name=slider]").slider({
                max: 90,
                min: 0,
                range: false,
                value: 45,
                step: 1
            }).slider("pips", {
                    first: "label",
                    last: "label",
                    rest: "label",
                    labels: sliderLabels,
                    step: 30
                    }).slider("float", {
                            labels: sliderLabels
                    });
`
The issue is that I need  slider with four labels like in var sliderLabels. Slider step should be "1" but labels over the four pips should be placed in "30" intervals. In result of code above is slider with four pips sa I need bu only first label is visilble, other three pips are without any label. 
How to solve this problem?

Thank you in advance for your answer.

**Comment by simeydotme** [comment]
it looks like it should work OK ?
I guess you closed the issue as it was your setup misconfigured?
