### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by deadlyw1re** [simeydotme/jQuery-ui-Slider-Pips#119]
This is my js:

```$(function() {
		var slider = jQuery("#slider");
		slider
			.slider({
				range: false,
				min: 50,
				max: 100,
				value: 50,
				step: 2
			})
			.slider("pips", {
				first: "label",
				last: "label",
				rest: "label",
				step: 1,
				labels: false,
				prefix: "",
				suffix: ""
			})
			.slider("float", {
				handle: true,
				pips: false,
				labels: false,
				prefix: "",
				suffix: ""
			});
	});```

If i set range to true, there is no problem but i dont want a range...

This code from the example page throws same error:

```
var slider = jQuery("#slider");
		slider.slider({
				min: 0,
				max: 100,
				step: 20
			})
			.slider("pips", {
				rest: "label"
			});
```

**Comment by simeydotme** [comment]
I have used your exact code here; http://jsfiddle.net/pyaedreL/ .. and it seems to work without issue.
Could you state which version of jQuery, jQuery UI and the jQuery Slider Pips you are using? :slightly_smiling_face:  

thanks.

**Comment by JaredDRobbins** [comment]
Has this issue been resolved?
I am seeing the same problem...

jQuery Version: 1.10.1
jQuery UI Version: 1.9.2
jQuery Slider Pips Version: 1.11.4
