### ISSUE TITLE
slider not slide-able on mobile device. 

### ISSUE THREAD

**Issue by cwonderingaround** [simeydotme/jQuery-ui-Slider-Pips#122]
Being loving this library and thank you very much for your hard work. 
However, I have a project recently are specific for iPad and I notice that the slider can only change the value by clicking.

Is there a way I can make this work on iPad? I would love to continue using this library.

**Comment by simeydotme** [comment]
https://github.com/simeydotme/jQuery-ui-Slider-Pips/issues/48
