### ISSUE TITLE
Clicking pips on a disabled slider should do nothing

### ISSUE THREAD

**Issue by hrobertson** [simeydotme/jQuery-ui-Slider-Pips#123]
The slider can be disabled with `$( ".selector" ).slider( "disable" );` or setting `disabled: true` in the options on initialisation.

While disabled, the handle(s) cannot be dragged and clicking on the slider does nothing.
However, clicking on a pip moves the slider to that pip. This is incorrect behaviour.

**Comment by simeydotme** [comment]
thanks!

**Comment by hrobertson** [comment]
@eukraina If you want to see this fixed, do it yourself and create a PR.
@simeydotme is under no obligation to fix this for you.

**Comment by jamesalee97** [comment]
> 
> 
> @eukraina If you want to see this fixed, do it yourself and create a PR.
Best answer ive ever seen)))) So why YOU do not fix it?

**Comment by hrobertson** [comment]
@jamesalee97 Because I don't use it. When I reported the bug I was just evaluating it and I think I ended up using something else. Can't remember though.

**Comment by simeydotme** [comment]
Cheers @hrobertson , for both the issue and the response.

---
To anyone who needs this fixed;  **please drop a +1 / 👍 on the issue so I can see if I need to invest time for y'all.** Or if someone else would love to contribute I'll happily review.

--- 
@eukraina; 
### 🖕


---

### Elaboration;

As @hrobertson has identified; 
- There's the possibility he could have looked at it himself if he was in desperate need (he may already have done it locally, who knows). 
- Someone else who also needed it, might have been able to supply a patch.
- Or the community could have given some 👍+1's to raise awareness of the need for a fix.

There's no obligation, or precedent, for open source code to be bug-free or heavily maintained. That being said, I don't feel good about neglecting my work, but I sure as hell don't need smart-ass comments from someone who's only contribution is; "shame on you". 

The industry is moving away from jQuery plugins, and especially jQueryUI, anyway. So I don't really know if it's worth my time. I'm interested in [re-creating the component with VueJS](https://codepen.io/simeydotme/pen/MZmGBa).

I'll attach a label for "Help Welcome". 
Please keep un-constructive comments to yourselves.

**Comment by simeydotme** [comment]
up to anyone still around;

https://github.com/simeydotme/svelte-range-slider-pips 
^ a modern version which should work in all environments (jquery, vanilla, vue/svelte/react)
