### ISSUE TITLE
Is It possible to disable specific pips in a slider ?

### ISSUE THREAD

**Issue by sharathbangera6** [simeydotme/jQuery-ui-Slider-Pips#124]
Hi,

Is there any way to disable specific pips in a slider. clicking on those pips shouldn't be allowed and the labels should be in some other color.

**Comment by sanjshah** [comment]
Hi,

I would also like to know if this is possible.

Thanks

**Comment by simeydotme** [comment]
hi, if you mean non-interactive (but slider can still stop at that pip) **then yes; use CSS.**
if you mean make the slider skipping certain pips only; **then no.**
if you mean make the slider skipping every nth pip; **then yes; use `pipstep`**
