### ISSUE TITLE
Need label between center

### ISSUE THREAD

**Issue by belgiumny** [simeydotme/jQuery-ui-Slider-Pips#126]
Hi @simeydotme  ,
Its is possible to put lable between slider and some another another between color line. 
ref is : [james Allen](https://www.jamesallen.com/loose-diamonds/all-diamonds/?Cut=Good,Very+Good,Ideal,TrueHearts) cut slider.  please create a fiddle if possible. if struggling from last 20 days for the same. tried every possible slider to achieve but no luck. 

i tried the same with ion slider but not working i put the question on stackover flow also but no result. 
stackoverflow : [question](https://stackoverflow.com/questions/58452734/ion-range-slider-is-not-working-with-center-label)

JSfiddle : [ion slider](https://jsfiddle.net/rudratosh/7wg1p86e/3/)

**Comment by simeydotme** [comment]
Hi @belgiumny  sorry you've had so much trouble.

This should be fairly simple with the slider pips.
http://jsfiddle.net/dxvhpjyq/

I basically gave the slider some pips. Made the pips be 25% of the slider width _(as we know there's only 4 options in this case)_ and then moved the `line` element to the end of the `pip` and made it 30px tall to cover the slider.

You may add any additional styling choices yourself with CSS.
SliderPips plugin is supposed to be mostly customized with CSS :)
