### ISSUE TITLE
How to add a line to follow handler value when Dragging & Click on label

### ISSUE THREAD

**Issue by Anzil-Aufait** [simeydotme/jQuery-ui-Slider-Pips#128]
**I want to add a line to follow handler value when slider value change.** 

When dragging line **width** update correctly but when I click on the **pips labels** it's not updating correct value, it's only update on the second click. 

**[Here is the demo](https://codepen.io/AnzilkhaN/pen/YzGJBZK?editors=0010)**

**Is there any better way to do the same ??** 

Anyway thanks for the awesome plugin.

**Comment by simeydotme** [comment]
hi @Anzil-Aufait 

I wonder if you read the documentation site clearly?
There's some examples [of "Range" sliders with "Min" range here](http://simeydotme.github.io/jQuery-ui-Slider-Pips/#styling-flat)

Either way, I've edited your Codepen to achieve what you want.
https://codepen.io/simeydotme/pen/739c42dc536635870f71ca336255c026

**Comment by Anzil-Aufait** [comment]
Hello, 
Thank you for the reply. 

**Is there any option for RTL.** 

I'm using `custom labels` in pips for RTL usage. I want `slider step: 1 & pips step: 5` with custom pips label.

But when I'm using the custom label & step for pips it's not working perfectly.

[**Here is the demo**](https://codepen.io/AnzilkhaN/pen/YzGJBZK?editors=0110)

Also, I'm not using the `"range" option` for value change, because I don't know its have support for RTL.

Please check. 

Thank you.
