### ISSUE TITLE
Deprecation installation warning. gulp-util@3.0.8

### ISSUE THREAD

**Issue by RALGIE** [simeydotme/jQuery-ui-Slider-Pips#129]
When I install the package I get a deprecation warning.

npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by simeydotme** [comment]
thx, but I won't bother fixing this as I consider this project past it's use-by date ;) 
please see https://github.com/simeydotme/svelte-range-slider-pips for a more modern version _(compatible with jQuery, Vue, React, Svelte, Vanilla)_
