### ISSUE TITLE
I do not know how to set up the jQuery-ui-Slider-Pips

### ISSUE THREAD

**Issue by si22si** [simeydotme/jQuery-ui-Slider-Pips#19]
I am a beginner.
The issue which I have is, I did which jQuery-ui-Slider-Pips homepage written, but there is nothing happened.
Then, I included the js&css which written in http://jqueryui.com/slider/#steps, and the slider without pips appared.

Help me please!

**Comment by ukuser34** [comment]
The reason this failed was because it wasn't within a `$(document).ready(function() { // call slider here })`
