### ISSUE TITLE
Figuring out the `step` parameter

### ISSUE THREAD

**Issue by lolmaus** [simeydotme/jQuery-ui-Slider-Pips#26]
Hi!

My jQuery UI Slider has varying `min` and `max` fields. They can go from zero to millions, based on user's preference.

Here's the code that configures the vanilla `step` parameter`:

```js
var slider_step = 10000;
_([100, 500, 1000, 5000, 10000, 100000, 1000000]).forEach( function(value){
    if ((slider_max - slider_min) <= value) {
        slider_step = value / 100;
        return false;
    }
});

$slider.slider({min: slider_min, max: slider_max, step: slider_step});
```

I. e. the vanilla `step` is proportional to the slider's range.

How do i define the Pips `step` parameter so that it displays the same (or at least mostly the same) number of pips regardless of the vanilla `min`, `max` and `step` parameters?

**Comment by simeydotme** [comment]
Let me know if http://simeydotme.github.io/jQuery-ui-Slider-Pips/#example-steps is good enough, @lolmaus :smile:

**Comment by lolmaus** [comment]
Woah, that's some awesome doc page! O_O

**Comment by simeydotme** [comment]
Thanks bro!.:) styling section coming soon :)
