### ISSUE TITLE
ui-slider-pip-selected doesn't respect slider value

### ISSUE THREAD

**Issue by JamesDonnelly** [simeydotme/jQuery-ui-Slider-Pips#30]
In the latest version of this a class of "ui-slider-pip-selected" gets added to the selected pip. However this doesn't respect the actual selected value of the slider.

I have a slider which has three labels, one, two and three. I'm preventing three from being selected with the following change event on the slider:

```
change: function (event, ui) {
    if (ui.value == 2) {
        $(this).slider('value', 1);
        return false;
    }
}
```

The problem is that this isn't reflected by the pips plugin, and despite the value "three" not being selected on the slider, pips seems to think it is.

![Example](https://cloud.githubusercontent.com/assets/2203377/4248665/95b21d02-3a69-11e4-8af2-65ccaf4ca677.png)

Here is a JSFiddle demo showing this in action: http://jsfiddle.net/oxfqoqhk/

**Comment by pgroot91** [comment]
You can animate it also with css!

`transition: left 0.15s;`
