### ISSUE TITLE
Missing documentation words about required empty div tag

### ISSUE THREAD

**Issue by boazrymland** [simeydotme/jQuery-ui-Slider-Pips#38]
Documentation bug: just add the fact that this widget expects an empty div, and not, as used in many other "slider enhancements" input element (hidden or 'range'). After changing my 'input' tag to 'div' (not forgetting to close it...) it worked. It took me lots of time to get this to work - not only this issue, but others, some on my end. 
Anyhow, adding this to the 'usage' section could be nice. I'll do it in a PR...

**Comment by shaildegoam** [comment]
Hi,
Since this slider is built with a div tag, how do I post data using a div tag? Thank you for the slider, it is just what I was looking for.

**Comment by shaildegoam** [comment]
Also, I have more than one sliders on a single page. I could be able to show only one slider on a page. Please help.

**Comment by simeydotme** [comment]
you can use the `onslidechange` event to update a hidden input-field:
http://stackoverflow.com/questions/7523864/ui-slider-with-text-box-input
