### ISSUE TITLE
How to show the slider tip always on the right side of slider line?

### ISSUE THREAD

**Issue by msavov** [simeydotme/jQuery-ui-Slider-Pips#41]
I want to show  the slider tip always on the right side of slider line, not sliding with the ui-slider-handle ( like attached ) 

![slider](https://cloud.githubusercontent.com/assets/3843705/5550027/99cc0994-8b99-11e4-9cf2-f08c122aa4b2.JPG)

**Comment by sohanpal** [comment]
I want to show the the value always (not on hover) like this:- 
![isue](https://cloud.githubusercontent.com/assets/6726486/8590070/7fa38f9c-263a-11e5-8315-ea514a58bb29.png)

is it possible

**Comment by simeydotme** [comment]
https://github.com/simeydotme/jQuery-ui-Slider-Pips/issues/55
:)
