### ISSUE TITLE
Events documentation?

### ISSUE THREAD

**Issue by IslamMagdy** [simeydotme/jQuery-ui-Slider-Pips#42]
Why there're no documentation for the events, like slidechange ...etc?? It'd be very useful to add

**Comment by simeydotme** [comment]
@IslamMagdy - there are no events; my plugin is a purely visual layer on top of http://jqueryui.com/slider/ the documentation about the JQUI events is here: http://api.jqueryui.com/slider/

**Comment by IslamMagdy** [comment]
Allright. Thank you!
