### ISSUE TITLE
Use together 'step' and 'labels'

### ISSUE THREAD

**Issue by Luntegg** [simeydotme/jQuery-ui-Slider-Pips#44]
Why I can't use together 'step' and 'labels'? I need in scale from 0 to 100000 and I want have a few labels like "10 th", "30 th".. I can't use 'suffix' becouse it will be looks like "10000 th".

**Comment by Luntegg** [comment]
I write `formatLabel: function (val) { return val / 1000 + this.suffix}`, but I think idea 'step' and 'labels' is good too.

**Comment by simeydotme** [comment]
Thanks for contributing, @Luntegg :) - am I right in thinking you want something like:

```js
.slider({
    min: 0,
    max: 100000,
})
.slider("pips", {
    labels: [
        { 10: "10th" }, 
        { 30: "30th" },
        { 1000: "1,000th" }
    ] 
});
```

... hmmm, this is a nice idea, but I have one concern... specifically for you; a 100,000 item loop is going to be quite intense... probably will cause crash/hang for slow computers and IE < 9;

I will look in to it, in the mean time please feel free to elaborate and present a better example of your use-case and I may be able to find a better solution :)

Regards,
Simon.

**Comment by simeydotme** [comment]
actually, can you do a quick image of what it is you're trying to achieve? :smile:
