### ISSUE TITLE
Last label becomes 7.3500000000000005!

### ISSUE THREAD

**Issue by icasmIT** [simeydotme/jQuery-ui-Slider-Pips#46]
I've stripped the code down to the following, but for some reason the last label becomes '7.3500000000000005' instead of just 7.35, I can't see why.

```
<script src="https://code.jquery.com/jquery-2.1.1.js"></script>
<script src="https://code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.10.4/themes/flick/jquery-ui.css">
<script src="/js/jquery-ui-slider-pips.min.js"></script>
<link href="/css/jquery-ui-slider-pips.css" type="text/css" rel="stylesheet">

<div id="slider" style="width:50%;"></div>

<script>
	$("#slider").slider({ range: true, step: 0.01, values: [ 0.15, 7.35 ] });
	$("#slider").slider({ min: 0, max: 7.35 });
	$("#slider").slider("pips");
</script>
```

**Comment by icasmIT** [comment]
I figured it out; if I change the min value to 0.15 it works.Obviously the minimum value should have been within the range of values.

**Comment by simeydotme** [comment]
hi @icasmIT - actualy this probably is ___not___ an error :) http://api.jquery.com/Types/#Number

try this in your console:

```js

var x = 0.15;
while( x < 7.35 ) {
    console.log(x);
    x = x + 0.01;
}
```

This is called floating-point precision and it's a pain in the arse. lol. It's actually occurring in the jQueryUI Slider itself and not my plugin (I believe) .. this will always happen when you use floating points.

You may wish to look at another plugin if you __really__ need to increment by 0.01 , or I can investigate if there's a way around this :smile: 

Simon.
