### ISSUE TITLE
How to submit slider values via Form

### ISSUE THREAD

**Issue by fcferreira29** [simeydotme/jQuery-ui-Slider-Pips#47]
Hello,

I am currently using this slider, and i was wondering if there is a way to send the values via form to another page,

i know that i can insert the values into hidden input fields,

is there any other way?

Thanks in advance,

Fabio Ferreira

**Comment by simeydotme** [comment]
Ajax? - this is a generic web-technology question, not an issue or bug... I'm going to close this but feel free to post a link to your www.stackoverflow.com question when you create it and I'll see if I can help over there :smile: 

Simon.
