### ISSUE TITLE
Click on Slider Pip Value Events

### ISSUE THREAD

**Issue by DavidRobb** [simeydotme/jQuery-ui-Slider-Pips#51]
On clicking a slider pip label I get multiple (too many) slide events but no slidestop event.

**Comment by simeydotme** [comment]
@DavidRobb , hi, thanks for contributing!! :)

Great spot, but lets quickly discuss what you'd expect to see in regards to the events.
I guess currently there definitely is a double event being fired, this is undesirable, so lets add:

Bugfix:
- [ ] __Remove duplicate event being fired.__

Secondly, I think we should aim to emulate the current event system: (mousedown: `start`, `slide`... mouseup: `stop`, `change`)

Feature Addition:
- [ ] __Emulate events/interactions from parent slider__

I'll add this to the 1.9 milestone :smile: - feel free to add, amend or discuss.
Simon.
