### ISSUE TITLE
open popup using the UI slider and update the value of the selected range

### ISSUE THREAD

**Issue by impulsedl** [simeydotme/jQuery-ui-Slider-Pips#52]
HI, 
I am very new in jquery and was trying to make a slider to open a popup with the selected range value.
Created a fiddle here:  (Want to open popup when I click or drag the slider range, let say if its 2 then the popup should open and the selected range value update to the popup)
http://jsfiddle.net/impulseinflame/j0bjc94y/34/
Output http://jsfiddle.net/impulseinflame/j0bjc94y/28/

Please Please help!!

**Comment by simeydotme** [comment]
http://jsfiddle.net/6a2fwusj/1
(updated to version 1.9.0, as it has a couple of small fixes)

:)
