### ISSUE TITLE
dragging a slider handle and releasing the mouse button on a label doesnt stop dragging

### ISSUE THREAD

**Issue by lionel87** [simeydotme/jQuery-ui-Slider-Pips#54]
Im not sure if this bug is related to this plugin or its a jQuery UI Slider bug, but when I drag the slider handle and release it on a label, the slider handle doesnt get released and follows my mouse x coordinate until I click on something on the page.
Tested with IE10 and Firefox 31.6.

**Comment by simeydotme** [comment]
Hey @lionel87 , thanks for this bug report!
You're right it's pretty bad behaviour in IE... I will investigate and see if I can patch it. 
It happens any time you click on a label, in fact.

Simon.

**Comment by simeydotme** [comment]
Fixed in the latest patch :)
https://github.com/simeydotme/jQuery-ui-Slider-Pips/releases/tag/v1.9.2

Thanks again, @lionel87 - I never use IE/FF daily, so I missed that shenanigans.

**Comment by lionel87** [comment]
Thanks for your work, your plugin is awesome. :) I really appreciate it!

**Comment by simeydotme** [comment]
:bow: :+1:
