### ISSUE TITLE
How to keep the floats always visible?

### ISSUE THREAD

**Issue by shahvaiz** [simeydotme/jQuery-ui-Slider-Pips#55]
I'd like to style the floats so that they are always visible. Currently, they are only visible upon hovering. When you click away from the slider, the floats disappear.

In your "5% interval" example in the docs, the floats are always visible. Can you please point me to the CSS style where I can achieve this?

Js Fiddle:
https://jsfiddle.net/shanif/zpm391dq/

Thanks!

**Comment by simeydotme** [comment]
hi @shahvaiz , the code to achieve it is right there on the docs site :)
http://simeydotme.github.io/jQuery-ui-Slider-Pips/#example-steps-fivepercent
just click the CSS tab above the slider.

Simon.
