### ISSUE TITLE
smooth animation on ui slide handle missing

### ISSUE THREAD

**Issue by raDiesle** [simeydotme/jQuery-ui-Slider-Pips#57]
Hi,

any idea:
with a simple example page, the slider will not move smooth like in your examples.
I checked code for css3 transitions and jscode but havent found anything.

```html
<script src="https://code.jquery.com/jquery-2.1.1.js"></script>
<script src="https://code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<script src="jquery-ui-slider-pips.js"></script>
                
<link rel="stylesheet" href="https://code.jquery.com/ui/1.10.4/themes/flick/jquery-ui.css">
<link rel="stylesheet" href="jquery-ui-slider-pips.css">

<div class="slider"></div>
<script>
$(".slider").slider().slider("pips");
</script>
```

**Comment by simeydotme** [comment]
It's not my plugin which controls this, read over the JQUI API for the `$.ui.slider`... it's an option called `animate` :smile:

**Comment by raDiesle** [comment]
It's dangerous to show not the real code on page :D 
anyway nice work!

**Comment by simeydotme** [comment]
Noted, but I have a _lot_ of sliders in the documentation, so I set the default value using a different approach which applies the property to every slider; this would be confusing and beside the point of documenting my plugin's features :)

([check line 6](http://simeydotme.github.io/jQuery-ui-Slider-Pips/dist/js/examples.js))

```js
        $.extend( $.ui.slider.prototype.options, { 
            animate: "fast"
        });
```
