### ISSUE TITLE
Dependancy name "jqueryui" vs. "jquery-ui"

### ISSUE THREAD

**Issue by bestage** [simeydotme/jQuery-ui-Slider-Pips#58]
Why are you actually using "jqueryui" instead of "jquery-ui"?
In my project another component (jqueryui-touch-punch) adds  jquery-ui, so I end up with 2 jquery UI folders under bower_components. 

Check it here
https://github.com/furf/jquery-ui-touch-punch/blob/master/bower.json

**bower install jquery-ui-slider-pips --save**

bower jquery-ui#~1.11.4         cached git://github.com/components/jqueryui.git#1.11.4
**bower jquery-ui#~1.11.4       validate 1.11.4 against git://github.com/components/jqueryui.git#~1.11.4**
bower jqueryui#>=1.9.2          cached git://github.com/components/jqueryui.git#1.11.4
**bower jqueryui#>=1.9.2        validate 1.11.4 against git://github.com/components/jqueryui.git#>=1.9.2**
bower jquery-ui-slider-pips#*   cached git://github.com/simeydotme/jQuery-ui-Slider-Pips.git#1.10.3
bower jquery-ui-slider-pips#* validate 1.10.3 against git://github.com/simeydotme/jQuery-ui-Slider-Pips.git#*
bower jqueryui#>=1.9.2         install jqueryui#1.11.4
bower jquery-ui#~1.11.4        install jquery-ui#1.11.4

**Comment by simeydotme** [comment]
@bestage -- easier to type? hahah...

No actually I was never aware that the official bower library is `jquery-ui` .. i used the CLI to search for `jqueryui` originally and it returned the correct repository, so I just went with that. :smile: 

I'll sort it out in the next day or so, apologies for any inconvenience :bow: 

Si.
