### ISSUE TITLE
Adding bigger range

### ISSUE THREAD

**Issue by cinghaman** [simeydotme/jQuery-ui-Slider-Pips#61]
Hi, i have been trying to add range from 0 to 35,000 at multiple of 10,000 but i am not able to get the desired result, and i want my max range (35,000 to be something like 35,000 & Above), how to go about it. 

```js
$("#circles-slider")
    .slider({ 
       min: 0, 
        max: 35000, 
        value: 10000
    })
    .slider("pips", {
        rest: "label"
    });	
```

**Comment by simeydotme** [comment]
should be:

```js
$("#circles-slider")
    .slider({ 
        min: 0, 
        max: 35000, 
        value: 10000
    })
    .slider("pips", {
        rest: "label",
        step: 10000
    }); 
```

However... I would __STRONGLY__ advise against having a slider that can go from 0-35,000 ... that's a big amount of numbers to loop over. -- Maybe you can create a JSFiddle and explain your desired result... else your UX could be pretty bad. Especially on older browsers.

**Comment by cinghaman** [comment]
hey thanks for quick reply, got it working using (The main reason for this was that the slider is for selecting salary range of a employee. 
var work = ["0", "10,000", "15,000", "25,000", "35,000 & Above"];

	$("#circles-slider")
                    
    .slider({ 
        max: work.length - 1, 
        min: 0,
        value: 1
    })
                    
    .slider("pips", {
         rest: "label",
		labels: work
    });

**Comment by simeydotme** [comment]
Great! :)
