### ISSUE TITLE
Changing the `max` option of the jquery-ui slider, does not update the the pips

### ISSUE THREAD

**Issue by Dignifiedquire** [simeydotme/jQuery-ui-Slider-Pips#62]
See http://jsfiddle.net/gLeh6rqh/2/ for details.

**Comment by simeydotme** [comment]
You should now be able to updat the pips simply by calling the `.slider("pips")` and/or `.slider("float")` methods again once you've changed the settings.

Unfortunately, the core slider does not expose/trigger an event when you update a setting, so I cannot hook in and automatically update the pips.
