### ISSUE TITLE
Problem with .ui-slider-tip and prefix/suffix

### ISSUE THREAD

**Issue by onokazu** [simeydotme/jQuery-ui-Slider-Pips#63]
When I add prefix/suffix to float, prefix/suffix are displayed outside float because the width of .ui-slider-tip is set to 34px by default. However if I change this to width:auto, the float no longer aligns with the slider handle because the margin-left of .ui-slider-tip is set to -18px. 

Is it possible to dynamically calculate the correct position (margin-left) of float from its current width so that it is always displayed at the right position ?

Great plugin, by the way!

**Comment by simeydotme** [comment]
@onokazu , you found the one thing that bothers me! hehe. (also, thanks for the kind words)

It's possible to use JS to re-calc the position based on the size, but there's two reasons why I don't:

1) Performance. While dragging the handle around the a values have to update super fast, and currently the thing performs pretty well on modern browsers with `< 1000` pips... I don't want to damage that by doing calculations on the DOM, and then repaint the element every time. at-least not in the main plugin[1]

2) Design. Actually going from `1` to `10,000`and especially with a prefix/suffix, the widths of the floats can vary greatly.. which makes the design look funky as the basic css shifts it's size a bunch.

=====

[1] _You, however, can set the width to auto, yourself, and then use the `.on("slidechange")`or `.on("slide")`event yourself to re-calc the position using jQuery :)_

**Comment by onokazu** [comment]
Great, thanks for your quick response and clarification!

You're absolutely right about the performance issue and what I eventually did was to calculate the possible maximum length of the float on the server side and then set the CSS width property via javascript. 

Thanks again and keep up the great work!

**Comment by simeydotme** [comment]
nice solution! -- glad it owrked out for you!
