### ISSUE TITLE
Multiple ranges on one slider

### ISSUE THREAD

**Issue by cotillardq** [simeydotme/jQuery-ui-Slider-Pips#64]
I have a use case where it would be great to have the possibility of creating multiple ranges on one slider.
I'm my case I am trying to build a sleep pattern capturing form. some people do have split sleep pattern. for example, sleep from 10pm to 2 am and then again from 4am to 7am and then a nap from 3pm to 4pm.

**Comment by simeydotme** [comment]
I'm having difficulty to imagine your use-case, @cotillardq  :) -- if I understand correctly, then what you're asking for is to do with the actual slider plugin, not the pips... but you can kind of achieve it already...

Why don't you create a Stackoverflow question, and I'll give you the answer... it's not really an issue for Github :)

Si.

**Comment by simeydotme** [comment]
https://jsfiddle.net/aouk0zad/1/

**Comment by cotillardq** [comment]
Thanks really appreciate you taking the time to build an example.
--
Quentin Cotillard
Founding Partner | Chief Creative Technologist
ON|WARD

One Embarcadero Center 
Suite 500
San Francisco, CA 94111

quentin@onwardagency.com
office   +1 415 623 2016
mobile +1 415 694 2813

**Comment by simeydotme** [comment]
No problem, happy to help :)
