### ISSUE TITLE
Slider issue on mobile

### ISSUE THREAD

**Issue by meghlal** [simeydotme/jQuery-ui-Slider-Pips#65]
Slider working fine on pc but in mobile its not slide by dragging we have to tap it .. can u fix this so that we can  drag the slider to work on mobile ?

Thanks
Meghlal

**Comment by simeydotme** [comment]
Hey @meghlal -- I appreciate you trying to contribute :) , but it's common etiquette to do a quick search in the issue tracker for a solution before you create it! :)

https://github.com/simeydotme/jQuery-ui-Slider-Pips/issues/48
