### ISSUE TITLE
Range min handle goes beyond max handle (and vice versa) on label click

### ISSUE THREAD

**Issue by cbtdev** [simeydotme/jQuery-ui-Slider-Pips#66]
Please see this [jsfiddle](http://jsfiddle.net/8whecwe0/) for reference.

Setup: range is set to true and both values are equal

When a label is clicked, the "selected" handle will move regardless if min > max or max < min.

This is inconsistent with the jQuery UI slider behavior. Is this intended or am I missing something?

Thanks,
Kurt

**Comment by simeydotme** [comment]
Thanks! good find, I'll get on this as soon as possible. Seems introduced when added multi-handle handling :)
:bow:

**Comment by cbtdev** [comment]
Perfect! Thanks so much!

**Comment by cbtdev** [comment]
Works great! Thanks for the quick resolution!

**Comment by simeydotme** [comment]
:wink:
