### ISSUE TITLE
Request: Minified CSS File

### ISSUE THREAD

**Issue by Colin-R** [simeydotme/jQuery-ui-Slider-Pips#67]
Have a minified version of jquery-ui-slider-pips.css in the dist folder that includes the MIT license.

This would be save a couple of steps for some folks, and I'm sure you would like credit for your work.

**Comment by simeydotme** [comment]
closed by https://github.com/simeydotme/jQuery-ui-Slider-Pips/releases/tag/v1.10.8 :)
