### ISSUE TITLE
Slider issues on touch devices

### ISSUE THREAD

**Issue by msavov** [simeydotme/jQuery-ui-Slider-Pips#68]
Slider doesn't work perfect. You have to pause your finger on the slider first, then it will work (rather than immediately working upon fingers slide). If you do not pause your fingers, when you slide, the ipad will register the gesture as "history -1".

Is there any solution for this issue ? Thanks.

**Comment by simeydotme** [comment]
https://github.com/simeydotme/jQuery-ui-Slider-Pips/issues/48
