### ISSUE TITLE
change event when a label is clicked

### ISSUE THREAD

**Issue by Senn0** [simeydotme/jQuery-ui-Slider-Pips#69]
When using pips with labels, and clicking on a label, the change event that is triggered does not include originalEvent.

Version 1.7.4 is working fine, but with version 1.10.7 it seems to be missing.

```javascript
change: function (event, ui) {
    if (event.originalEvent) {
        // event is triggered by the user
    }
    else
    {
        //event is triggered manually
    }
}
```

So when manually setting some value, event.originalEvent is empty (this is correct):
```javascript
$(".slider1").slider("option", "value", 1);
```

When the user clicks on the label, there should be something in event.originalEvent (not correct at the moment).

using jQuery-ui 1.11.4 and jQuery 2.1.4

**Comment by simeydotme** [comment]
Hey @Senn0 , thanks for contributing... 

You'll have to convince me why clicking a label should be considered the *original* change event before I investigate this, and also could you produce a JSFiddle to demonstrate exactly what you're referring to? :smiley:

**Comment by simeydotme** [comment]
https://github.com/simeydotme/jQuery-ui-Slider-Pips/blob/master/dist/jquery-ui-slider-pips.js#L238-L259

The method was changed due to animation-issues, because triggering the "change" event caused the handles to jump, instead of animate.

**Comment by Senn0** [comment]
@simeydotme well, maybe it should not have the original change event, but I guess there should be some difference between manually setting a value (using the slider) and programmatically setting a value. So that it's possible to only execute something when the change is triggered manually.

If I have 2 sliders with the same class, I want to change them both when the other one changes.
I could use this in previous version:

```javascript
$(".slider1").slider({
        min: 1,
        max: 8,
        change: function (event, ui) {
            var people = ui.value;
            if (event.originalEvent) {
                $(".slider1").slider("option", "value", people);
                function_calculate_persons(people, true);
            }
        }
    }).slider("pips", {
        step: 1,
        rest: "label"
    });
```

Do you understand or do you want me to provide extra info?

I really like your plugin! :)

**Comment by simeydotme** [comment]
Hmmm... I have never come across `originalEvent` before, so I'm still a little hazy on how it works, or what it's purpose is... I can kind of guess... but I don't see it in the `jqui` core code or documentation.

why don't you test for:

`e.type === "slidechange"` instead ? :)

**Comment by Senn0** [comment]
I think I already checked that, but it was always slidechange, when setting manually or programmatically. But I'm not sure so I will double check.

**Comment by simeydotme** [comment]
no-no, you're right, it's always that value, I originally misunderstood your issue and edited my reply :)

**Comment by Senn0** [comment]
Yes indeed, If I don't use event.originalEvent, the change event will keep getting triggered :)

**Comment by jpotterm** [comment]
I'll help brainstorm some options:

1. Work around it by setting a boolean flag something like this:

```javascript
var recursing = false;

function change() {
}
```

**Comment by jpotterm** [comment]
I'll help brainstorm some options:

`1.` Work around it by setting a boolean flag something like this:
```javascript
var recursing = false;

function change() {
    if (recursing) {
        recursing = false;
    } else {
        recursing = true;
        // update slider
    }
}
```
`2.` The slider could provide a way to programmatically set its value without triggering events

Hopefully those ideas are helpful.

**Comment by simeydotme** [comment]
I'll try to look at this over the weekend... it might be that I have to add the `originalEvent` flag myself to the event parameters. It's a tricky situation. -- thanks for chipping in @jpotterm ! :)

**Comment by simeydotme** [comment]
hey @Senn0 :) -- sorry this took so long, I really hope you're still using the plugin and please check the newest release `1.11.1` for the fix, see what you think! :)

**Comment by Senn0** [comment]
Hi @simeydotme, I'm certainly still using this plugin :-). Thank you for the fix, I will check it tomorrow!

**Comment by mrneilalan** [comment]
Thank you for this fix.  I rely on originalEvent to know if I need to process sliderchange handler.  This is a big help.
