### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addClass' of undefined

### ISSUE THREAD

**Issue by ScottSpittle** [simeydotme/jQuery-ui-Slider-Pips#73]
Seem to occasionally get this error when clicking on the various stepping points.

```
Uncaught TypeError: Cannot read property 'addClass' of undefined
```

**Comment by simeydotme** [comment]
Can you reproduce it consistently in the newest release, @ScottSpittle ? :) -- please could you [fork this JSFiddle and see if you can reproduce](http://jsfiddle.net/simeydotme/Lh6pygef/) -- and tell me which browsers.

Best, Simon.

**Comment by ScottSpittle** [comment]
I'll try tomorrow and let you know. Thanks for the response.

**Comment by ScottSpittle** [comment]
Looks OK with v1.10.5

**Comment by simeydotme** [comment]
Excellent, that's great news! 
Thanks so much for taking the time to raise, and then retest the issue! :bow: :grin:

**Comment by ScottSpittle** [comment]
Thanks for your time.
