### ISSUE TITLE
Label click issue with "min" or "max" range

### ISSUE THREAD

**Issue by sepster** [simeydotme/jQuery-ui-Slider-Pips#76]
In my code the range of the slider is initially set as true. Then depending on user input, the range of the slider is sometimes changed from true to "min" or "max" ( http://api.jqueryui.com/slider/#option-range )

After the range change, clicking on the slider itself still works. However, when clicking on a label, the slider is not changed. I think the problem is in jquery-ui-slider-pips.js in labelClick function:

                if ( values && values.length && slider.options.range === true) {

                    slider.element.slider("values", indexToChange, val );

                } else {

                    slider.element.slider("value", val );

                }

For some reason, the values array still has two values and therefore slider is called with "values" instead of "value". This causes "Uncaught TypeError: Cannot set property 'undefined' of null" in jquery-ui.js because this.options.values is null in values function on row:
this.options.values[ index ] = this._trimAlignValue( newValue );

As a quick fix I modified a row in labelClick function from this:
if ( values && values.length) {
to this:
if ( slider.options.values && slider.options.values.length ) {

I'm not sure if this is a proper way to fix the problem. Perhaps the values array should be updated somewhere? It seems that the same values array is also used elsewhere in jquery-ui-slider-pips.js so I'm guessing those also need to be updated.

Note: If the slider range is initially set as "min" or "max" then the problem does not occur, because values array is empty. The problem only occurs after switching the range from true to "min" or "max".

**Comment by simeydotme** [comment]
I'll look in to this more when I get back home to Hong Kong, currently on holiday.... But I would say the best thing to do, for now, is to re-init the pips after you chnage the slider... There may be other issues as well you're unaware of, so better to reinit :)

**Comment by simeydotme** [comment]
http://simeydotme.github.io/jQuery-ui-Slider-Pips/#refreshing
That should help you :) -- you'll need `1.11.1` :)
