### ISSUE TITLE
Labels above and below slider

### ISSUE THREAD

**Issue by YiuriV** [simeydotme/jQuery-ui-Slider-Pips#77]
Hello, I need to create a slider with labels above and below the slider. At the moment I have this code:

var dates = ["1637", "1756", "1777", "1846", "1855", "1865", "1912", "1973", "1979", "2013", "2015"];       
$(".tinkerslider")              
     .slider({ 
        	min: 0, 
        	max: dates.length-1, 
        	value: 3 
    	})          
    	.slider("pips", {
                rest:"label",
        	labels: dates
    	})                    
    	.slider("float", {
      pips:false,
        	labels: [ "Sanderus-Hondius", "Malfeson", "Ferraris", "VDM", "Gerard", "Popp", "Compijn & Soenen", "MOW", "Foto", "Foto", "GRB" ]
    	});

However, I need to create a slider as the one in the attached image. Right now I have the dates below the slider and the labels with names as a popup when I click on the right year, but as you can see I need those names to be fixed above the slider. Any idea how I can achieve this? 

Thanks alot, Julie

![slider](https://cloud.githubusercontent.com/assets/6714529/10734034/97b37602-7c01-11e5-9dff-efa08b949176.png)

**Comment by simeydotme** [comment]
Hi, Julie :)
If you set `"pips"` to `true` on the float method, you could then use CSS to show the floats permanently and position them above the slider :) .. If you havent figured it out before I get back to Hong Kong (im on holiday) then I'll give you a proper example :grin:

**Comment by simeydotme** [comment]
here, @YiuriV :) try this:
http://jsfiddle.net/zkxt1cds/

**Comment by simeydotme** [comment]
Added this to documentation website, with a little change to styling :smile: 
http://simeydotme.github.io/jQuery-ui-Slider-Pips/#styling-double

**Comment by YiuriV** [comment]
thanx for the solution :) had to change my whole coding though as my boss wanted a completely flexible time-line (no known start or end, dynamic data from json, zooming in and out on the timeline).
