### ISSUE TITLE
How to change tooltip value ?

### ISSUE THREAD

**Issue by LeoRegulus** [simeydotme/jQuery-ui-Slider-Pips#78]
Hi, i want to change tooltip value for example label value "November" and i want to change tooltip value "3.11.2015" how can i do that.

Thank you.

**Comment by simeydotme** [comment]
Please get familiar with the documentation, first :) http://simeydotme.github.io/jQuery-ui-Slider-Pips/#customisation-options

But you just supply a different array of values to the `float` method.

```js
var year = new Date().getFullYear();
var labels = [ "January" , "February" ... ];
var floats = [ "03.01." + year , "03.02." + year ,  ... ];

$("div")
    .slider({ min: 0, max: 11 })
    .slider("pips", { labels: labels, rest: "label" })
    .slider("float", { labels: floats });

```

Hope this helps :smile:
