### ISSUE TITLE
Irregularly-spaced pips

### ISSUE THREAD

**Issue by alpha-beta-soup** [simeydotme/jQuery-ui-Slider-Pips#79]
My use case: I want a slider allowing a user to select a point in time for which data can be presented on a map (a forecast). The time steps from `t=0` into the future are not required to be regularly-spaced: it may be that there are forecasts every hour for 24 hours, and then only two per day out to 7 days. In reality, the steps can be arbitrary, so I can't rely on any pattern. I would like to display a slider with pips spaced appropriately: a regular spacing would not indicate the irregular nature of the forecasts across time. Perhaps passing pips as a list of proportions, `[0, 0.05, 0.1, 0.15, 0.2, 0.4, 0.6, 1]`, indicating where they should be placed along the slider. Is this functionality currently provided? I couldn't find anything in the documentation to suggest it is, as pips always seem to require a single multiplicative step.

**Comment by simeydotme** [comment]
@alpha-beta-soup , thanks for contributing :)
I would find it easier to answer if I saw an image of what you're trying to achieve... but for now I think this is your case:

You have a slider with regular intervals, but you only want pips to show at certain (arbitrary) places?

My suggestion would be to use css/js to show them...

perhaps something like:

```css
.myslider.ui-slider-pips .ui-slider-pip {
    display: none; }
```

```js

$(".myslider")
    .slider({ max: 100 })
    .slider("pips", { rest: "label" });

var i,
    show = [1, 4, 7, 9, 19, 54, 98]; // arbitrary pips to show
    $pips = $(".myslider").find( ".ui-slider-pip"); // hold all the pips for filtering

for( i = 0; i < show.length; i++ ) {
    $pips.filter( ".ui-slider-pip-" + show[i] ).show();
}
  
```

**Comment by alpha-beta-soup** [comment]
Actually the slider has irregular intervals as well. Imagine that there are forecasts available for now, in three hours, in six hours, in a day, in two days, in four days, and in seven days. That is what I mean by an irregular interval. Visually, something like this:

![screenshot from 2015-11-17 15 58 04](https://cloud.githubusercontent.com/assets/5925045/11201582/3437d9ca-8d44-11e5-97d1-4cbcb94c2cb9.png)

There is a continuum of possible values, but because the duration of time between available forecasts is not constant, I do not want to present them as a regular interval, nor allow users to select an intermediate point on the slider.

Your example has been very helpful for me (reasonably new to web development):

![screenshot from 2015-11-17 16 31 47](https://cloud.githubusercontent.com/assets/5925045/11202044/cb12e57a-8d48-11e5-977a-808c7329b6e4.png)

I'll post a complete snippet from my coffeescript code in case it helps anyone else. Let me know if you'd like this added to any documentation, I can make a PR as thanks.

```coffeescript
make_slider = (values, step, slider_class, slider_id) ->
    s = $(".#{slider_class}")
    .slider
      min: Math.min.apply(Math, values)
      max: Math.max.apply(Math, values)
      step: if step? then step else 10800 # Smallest step present in values
    .slider "pips",
      first: 'label'
      last: 'pip'
      rest: 'pip'
      labels: moment.unix(t).fromNow() for t in values
    $pips = $(".#{slider_class}").find(".ui-slider-pip") # Hold all the pips for filtering
    $pips.filter(".ui-slider-pip-#{val}").show() for val in values
```

Which compiles to:

```javascript
make_global_slider = function(values, step, slider_class, slider_id) {
    var $pips, j, len, results, s, t, val;
    s = $("." + slider_class).slider({
      min: Math.min.apply(Math, values),
      max: Math.max.apply(Math, values),
      step: step != null ? step : 10800
    }).slider("pips", {
      first: 'label',
      last: 'pip',
      rest: 'pip',
      labels: (function() {
        var j, len, results;
        results = [];
        for (j = 0, len = values.length; j < len; j++) {
          t = values[j];
          results.push(moment.unix(t).fromNow());
        }
        return results;
      })()
    });
    $pips = $("." + slider_class).find(".ui-slider-pip");
    results = [];
    for (j = 0, len = values.length; j < len; j++) {
      val = values[j];
      results.push($pips.filter(".ui-slider-pip-" + val).show());
    }
    return results;
  };
```
