### ISSUE TITLE
How to change the value of slide on entering the value in form text box??

### ISSUE THREAD

**Issue by veeramanik** [simeydotme/jQuery-ui-Slider-Pips#82]
Hi,
I have a functionality to change the slide values on entering the number/values in input text field.
I have attached the below image for you reference.Please give your suggestion to solve this issue.

code:
$("#horizontalRangeslider")
                        
    .slider({ 
        min: 0, 
        max: 100, 
        range: true, 
        values:5,
		step:5
		
    })
                        
    .slider("pips", {
        rest: "label",
		step:2
    })
                        
    .slider("float");

![image](https://cloud.githubusercontent.com/assets/16466124/12022408/80f8a884-adb5-11e5-84de-2dfef90d8fee.png)

Thanks,veera

**Comment by simeydotme** [comment]
Sorry, @veeramanik ... what's the problem ? :)

**Comment by veeramanik** [comment]
is it possible to trigger the slider function when entering the values directly in the given input box??

**Comment by veeramanik** [comment]
For example: If I enter 5 in the input text box, the slider position  should move to  5. If I enter 10 in the input text box, the slider should move to 10.  @simeydotme

**Comment by simeydotme** [comment]
yes, but it's not a function of the slider... you just need to write your own code...
Here, I've done a good example for you:
http://jsfiddle.net/qt7qs4pn/3/

In return, would you mind sharing your app / design when you're done :) I really like the style and think it would be a good addition to the examples on my documentation :)

**Comment by veeramanik** [comment]
Thanks dude..Its working !..Sure i will share once i have completed the design..
