### ISSUE TITLE
Shifting range

### ISSUE THREAD

**Issue by szmarci** [simeydotme/jQuery-ui-Slider-Pips#83]
Would it be possible with your plugin to shift range? I mean you can't drag the handles, you can only drag the range itself, thus shifting the start and endpoint simultaneously.

**Comment by simeydotme** [comment]
sorry @szmarci that's core slider functionality, nothing to do with pips/floats :smile: -- a little googling come up with:

http://stackoverflow.com/questions/5955343/drag-the-range-of-a-ui-input-range-slider/6095941#6095941
