### ISSUE TITLE
touchscreen compatibility

### ISSUE THREAD

**Issue by rishabh00100** [simeydotme/jQuery-ui-Slider-Pips#85]
I loved your sliders that you posted on simeydotme.github.io/jQuery-ui-Slider-Pips
but they are not touch compatible it seems...I could not drag the handles to set values for range slider, instead I had to tap on various points along the slider to change value which is not very convenient on smaller devices.
Plz help

**Comment by GadgetUK** [comment]
Quick fix take a look at http://touchpunch.furf.com/

**Comment by simeydotme** [comment]
thanks @GadgetUK :)
