### ISSUE TITLE
Enumerated pip label values not outputting

### ISSUE THREAD

**Issue by hughbris** [simeydotme/jQuery-ui-Slider-Pips#86]
I think this may be a bug - when I [assign an array for the ('rest') list of pip labels, they do not render](http://jsfiddle.net/mv0p582f). I've tried a few combinatons of options and values, including:

* dropping some zeroes off those very large values
* making the values integers
* adding first and last labels

Curiously, the first pip label _does render_ as intended. Also note that the pip label prefix does show.

Further, I am pretty certain that this is not CSS, as the rendered markup in Firebug shows the value missing. (That is, the `span.ui-slider-label` does not contain that content.) So I think it's a fair assumption it's JQuery.

Or I'm completely missing something and doin' it wrong :/

**Comment by hughbris** [comment]
Have identified problem and solved it, at least for my requirements. Will package up (along with some unrelated tweaks) and issue as pull request.

Because I've only solved for my use case, please test more comprehensively before integrating the patch.

**Comment by simeydotme** [comment]
@hughbris ... I'll review the things you've done to understand soon...
in the meantime, have a quick google for: *git reflog* ... also you can just type; `git reflog` in your command line... it gives you direct access to your git history, allowing you to "jump back in time" to different things you did... it's a little different to jumping back to commits :)

**Comment by simeydotme** [comment]
sweet, good find!! :grin: 
the logic looks legit, but the style looks a bit off... if you don't mind I'll pull the fix locally and make a slight style tweak, then commit and you should get the credit , still :)

If you want any help/info on `reflog` and what it can do for you, join the gitter channel for jq-pips and I'll do my best!

:bow:

**Comment by simeydotme** [comment]
thanks @hughbris
