### ISSUE TITLE
 Please, publish the js data of the examples.

### ISSUE THREAD

**Issue by HansVanLeunen** [simeydotme/jQuery-ui-Slider-Pips#89]
Please also publish the js data of the more complex examples. Especially those that use multiple handles and special handle forms. These sliders are interesting for setting variable color gradients  and opacity gradients.

**Comment by simeydotme** [comment]
Thanks for the interest @HansVanLeunen :smile: 
But what exactly are you asking for? the code to create each example is shared on the documentation website alongside each and every example... :confused:

**Comment by HansVanLeunen** [comment]
Dear Sir,
I figured out how to download the webpage and the files, but I have difficulties in understanding how to insert this code into my application. I use WebMatrix as a development tool and this tool has very particular habits in making the js and css files available to the webpages. The Nuget loader has an obscure way of adding theme files and this often generates conflicts with initialization of widgets. The available WebMatrix documentation does not explain in detail how this system works. From the webpage on which the slider pips are introduced is not given any information when or whether the pips will be included in the standard support system. Still I am very interested in this extension of the standard jquery slider. It fits very well in my application, which concerns LED lighted lettering design and preview. I want to include an equivalent of the colorzilla color gradient generator in that design tool.
I still not comprehend how to properly initialize the jquery widgets in the realm of WebMatrix. A WebMatrix template for a starter site that demonstrates slider widgets (and other widgets) would be very helpful. Thanks for your help.
Sincerely yours,
Hans van Leunen, retired physicist, chemist and programmer.
http://www.e-physics.eu
----Origineel Bericht----
Van : notifications@github.com
Datum : 19/03/2016 16:22
Aan : jQuery-ui-Slider-Pips@noreply.github.com
Cc : hans.van.leunen@planet.nl
Onderwerp : Re: [jQuery-ui-Slider-Pips]  Please, publish the js data of the examples. (#89)
Thanks for the interest @HansVanLeunen  
But what exactly are you asking for? the code to create each example is shared on the documentation website alongside each and every example...
