### ISSUE TITLE
Show Current Value on Pip?

### ISSUE THREAD

**Issue by mehmetalidumlu** [simeydotme/jQuery-ui-Slider-Pips#90]
Hi,
I used vertical slider, it shows min and max value (1-21). But i cant view current value near slider.
There is a screenshot. How it show current value as in the screenshot?
Thanks...

[**Screenshot**](http://prntscr.com/arg7hi)

**Comment by simeydotme** [comment]
can you produce a `jsfiddle` example to demonstrate this?

https://github.com/simeydotme/jQuery-ui-Slider-Pips#want-to-contribute

**Comment by simeydotme** [comment]
like this?
http://jsfiddle.net/6wvwgp5c/

**Comment by mehmetalidumlu** [comment]
Yess, thanks for help...
