### ISSUE TITLE
Step method with data from array

### ISSUE THREAD

**Issue by roveek** [simeydotme/jQuery-ui-Slider-Pips#92]
I have this code:

`	var time = ['0:00', '0:30', '1:00', '1:30', '2:00', '2:30', '3:00', '3:30', '4:00', '4:30', '5:00', '5:30', '6:00', '6:30', '7:00', '7:30', '8:00', '8:30', '9:00', '9:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30', '13:00', '13:30', '14:00', '14:30', '15:00', '15:30', '16:00', '16:30', '17:00', '17:30', '18:00', '18:30', '19:00', '19:30', '20:00', '20:30', '21:00', '21:30', '22:00', '22:30', '23:00', '23:30', '23:59'];`

`	$("#alternating-slider").slider({
		min: 0,
		max: time.length-1,
		values: [10, 20, 30, 40]
	})
	.slider("pips", {
		rest: "label",
		labels: time,
		step: 2
	})
	.slider("float", {
		labels: time
	});`

Without "step", slider looks not so good.
So I have to add a "step". And now I see scale from 0:00 to 12:00. I think it should be from 0:00 to 23:59 without *:30.

http://jsfiddle.net/skupk5jp/2/

![2016 05 16](https://cloud.githubusercontent.com/assets/17777345/15281985/622330f2-1b59-11e6-91ac-becc6ec32ada.jpg)

**Comment by simeydotme** [comment]
something like this:
http://jsfiddle.net/skupk5jp/3/ ?

:)

please bear in mind that when you step the labels, it means it will apply labels only to each `nth` point on the slider... but it will always go through the labels in order.

If you're using a logical scale (like times) it's much better to use formatting. Labels for for "non-numeric" style sliders... eg: "Good", "Bad", "Ugly" :)
