### ISSUE TITLE
Scale pips are not applied correctly

### ISSUE THREAD

**Issue by StefanPerez** [simeydotme/jQuery-ui-Slider-Pips#94]
Hello. First of all thanks for this awesome extension. It is a really nice add-on but I have a problem which I can not figure out why.

I wanted to create a scaling slider without using a range. Now I have created a [Fiddle](https://jsfiddle.net/q1jaqojr/) to demonstrate.

for some reasons and I do not know why the pips for values 100 and 250 are not generated. Can you explain me why this is and how I could solve this?

My CSS code:
```
 #jqueryUiSlider .ui-slider-pip {
  top: 20px; }

  #jqueryUiSlider .ui-slider-pip .ui-slider-label {
    display: none;
    background: rgba(67, 77, 90, 0);
    color: #434d5a;
    border-radius: 4px;
    padding: 0.3em 0;
    width: 2.4em;
    margin-left: -1.2em;
    transition: all 0.2s ease-out; }

  #jqueryUiSlider .ui-slider-pip .ui-slider-line {
    height: 4px; }

  #jqueryUiSlider .ui-slider-pip:nth-of-type(1n+2) .ui-slider-line {
    height: 8px; }

  #jqueryUiSlider .ui-slider-pip:nth-of-type(1n+2) .ui-slider-line {
    height: 12px; }

  #jqueryUiSlider .ui-slider-pip:nth-of-type(2n+2) .ui-slider-label {
    top: 16px;
    display: block; }
```

**Comment by simeydotme** [comment]
:) thanks,
but it looks fine to me?

**Comment by StefanPerez** [comment]
Ah true! If you look the fildde in Firefox but not in Chrome! Did you looked at the fiddle in Chrome?

**Comment by simeydotme** [comment]
I did... however, there should be no reason Firefox displays it differently to Chrome... unless Firefox has f***ed up the selector engine in CSS...

![screen shot 2016-06-03 at 3 38 48 pm](https://cloud.githubusercontent.com/assets/2817396/15772036/5bc0fb30-29a1-11e6-8348-a64ff1c613a6.png)

But, it looks OK in Firefox, to me, too...

**Comment by StefanPerez** [comment]
Weird. When I look in Firefox everything just works fine. But if I look in Chrome I see this:
![capture](https://cloud.githubusercontent.com/assets/6696145/15772104/6d4280ae-296f-11e6-9a32-4bfa56d1d657.PNG).

After resize the screen the empty pips get moved to another value.

**Comment by simeydotme** [comment]
I have a video of me resizing in both FF and Chrome....

![pips](https://cloud.githubusercontent.com/assets/2817396/15772201/65334758-29a2-11e6-878e-c9b2c1742f1c.gif)

**Comment by simeydotme** [comment]
Although, I also notice that your "float" looks a bit weird.... have you zoomed in/out on the page?

**Comment by simeydotme** [comment]
Yep. that's totally it, you're zoomed at 90%....
That's not ever gonna work because 1px at 90% is not 1px... meaning you can't see the pips :)

**Comment by StefanPerez** [comment]
mmm then I have to check my environment because I see weird things haha! Anyways thanks for your help! You showed that it worked! I see that you are using a MAC. There should not be a difference between a Windows and a MAC viewing the PIPS right. I can not imagine that that would be the problem

**Comment by StefanPerez** [comment]
Ah you are my hero! It was the zoom! Man I feel so stupid haha. Thank you

**Comment by simeydotme** [comment]
No problemo... this happens all the time in QA, haha
