### ISSUE TITLE
Can ranges categorical instead of a sliding scale

### ISSUE THREAD

**Issue by sbhol2008** [simeydotme/jQuery-ui-Slider-Pips#95]
Can ranges categorical instead of a sliding scale: $0 - $1500, $1500 - $2500, $2500 - $5000, $5000 - $10,000, Please help

**Comment by simeydotme** [comment]
what? I think yes, if I guess your meaning... use the format / labels options :)

**Comment by sbhol2008** [comment]
Hi,
Actually this is step range slider, in 1st step : $0 - $1500, 2nd step : $1500 - $2500, 3rd step : $2500 - $5000, 4th step :  $5000 - $10,000 and 5th step $50000+, in custom label you can add one value. Hope you under stand.

**Comment by simeydotme** [comment]
@sbhol2008 you're asking for support not reporting a bug, please open a question on Stackoverflow, send me a link to it and I will answer it there :) -- that way we can help all future users who need support with this kind of problem.

Best, Simon.
