### ISSUE TITLE
Fix default value

### ISSUE THREAD

**Issue by cinek19** [simeydotme/jQuery-ui-Slider-Pips#96]
How can I fix a default value? I mean, if a bar have 2 pips, I want to fix one of them.

**Comment by simeydotme** [comment]
please try to explain better :)

**Comment by waxxxd** [comment]
I think cinek19 was saying 2 handles and one of them is unmovable.

**Comment by simeydotme** [comment]
@cinek19 I am going to assume your request is something about the jQueryUI Slider plugin, sorry I can't help.
