### ISSUE TITLE
Using step with float

### ISSUE THREAD

**Issue by kminhtri** [simeydotme/jQuery-ui-Slider-Pips#97]
Hi,

I use in my js the step parameter with a float (like "0.1") but I get some perturbation with float (i.e. : 3.1 next step become 3.1000000004). I think in the code we have to add "toFixed(1)" to avoid this problem with float.

`var s = $elem.slider({
            min: 3,
            max: 4,
            step: 0.1,
            value: scope.filter.value || 0,
            values: [scope.filter.minValue || 0, scope.filter.maxValue || 9],
            range: scope.filter.range || false
          });`

**Comment by simeydotme** [comment]
@kminhtri could you please provide a JSFiddle with an exmaple of what you're describing? However... I actually think this is just a normal JS / Floating Point Number issue which you must solve yourself.

http://floating-point-gui.de/

**Comment by kminhtri** [comment]
Yes in fact, it's the normal JS, you're right, but it's ugly for UX no? :p I will profide you tje JSFiddle nearly :)
